
services:
  postgres:
    image: postgres:15-alpine
    container_name: company_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: saso@2005
      POSTGRES_DB: companydb
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - company-network

  company-microservice:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: company-microservice
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/companydb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: saso@2005
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    networks:
      - company-network

volumes:
  postgres_data:

networks:
  company-network:
    driver: bridge

